[package]
name = "rust_publisher"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust_publisher"
path = "src/main.rs"

[dependencies]
r2r = "0.9"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"  